### ISSUE TITLE
Show timer for next token drop

### ISSUE THREAD

**Issue by nionis** [hoprnet/hopr-leaderboard#18]
**Describe the use case**
A clear and concise description of what problem the feature solves.

**The feature**
Describe the feature you'd like

**Comment by nionis** [comment]
@jjperezaguinaga please fill in this issue

**Comment by jjperezaguinaga** [comment]
See #28 for more information. This one is just a `30000`ms timer, obtained from `https://hopr-coverbot.firebaseio.com/basodino/state/env/COVERBOT_VERIFICATION_CYCLE_IN_MS.json`. To ensure that when the user loads you are in the right second (e.g. `relaying at 24, 23, 22, 21,...` instead of always showing `30, 29,28...` every page refresh), you need to use https://hopr-coverbot.firebaseio.com/basodino/state/env/COVERBOT_TIMESTAMP.json, which tells you from which moment the bot started to relay, and then divided it between 30 seconds using `Date.now` as a reference.

**Comment by jjperezaguinaga** [comment]
Closing as duplicate of #28
